# These are supported funding model platforms

github: blackbunny
open_collective: murat-kucukosman
ko_fi: lazysickartist
patreon: 
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding: 
